FROM ubuntu:20.04

LABEL maintainer="amminer@pdx.edu"

RUN apt update -y
RUN apt install -y python3-pip

COPY . /app

WORKDIR /app

RUN pip install -r requirements.txt

ENTRYPOINT ["python3"]

CMD ["app.py"]
